# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 14:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0002_delete_aldeiadigital'),
    ]

    operations = [
        migrations.CreateModel(
            name='AldeiaDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('descr', models.CharField(max_length=254)),
                ('folder', models.CharField(max_length=254)),
                ('status', models.CharField(max_length=254)),
                ('situacao', models.CharField(max_length=254)),
                ('tipo', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
