# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 14:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0003_aldeiadigital'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasRisco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicita', models.CharField(max_length=254)),
                ('cadastro', models.CharField(max_length=254)),
                ('risco', models.CharField(max_length=254)),
                ('problema', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
