# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 14:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0004_areasrisco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclovia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
