# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0007_lote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lote',
        ),
    ]
