# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 16:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0010_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrechoRodoviario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_objeto', models.FloatField()),
                ('nome', models.CharField(max_length=100)),
                ('nomeabrev', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=6)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
