# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 16:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0011_trechorodoviario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRA_Trecho_Rodoviario_L',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_objeto', models.FloatField()),
                ('geometriaa', models.CharField(max_length=3)),
                ('codtrechor', models.CharField(max_length=25)),
                ('tipotrecho', models.CharField(max_length=18)),
                ('jurisdicao', models.CharField(max_length=22)),
                ('administra', models.CharField(max_length=18)),
                ('concession', models.CharField(max_length=100)),
                ('revestimen', models.CharField(max_length=28)),
                ('operaciona', models.CharField(max_length=12)),
                ('situacaofi', models.CharField(max_length=13)),
                ('nrpistas', models.FloatField()),
                ('nrfaixas', models.FloatField()),
                ('trafego', models.CharField(max_length=12)),
                ('canteirodi', models.CharField(max_length=3)),
                ('capaccarga', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
