# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0012_tra_trecho_rodoviario_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tra_trecho_rodoviario_l',
            name='geometriaa',
            field=models.CharField(max_length=4),
        ),
    ]
