# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0014_auto_20160505_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tra_trecho_rodoviario_l',
            name='revestimen',
            field=models.CharField(max_length=29),
        ),
    ]
