# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0016_auto_20160505_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TRA_Trecho_Rodoviario_L',
        ),
    ]
