# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 17:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0017_delete_tra_trecho_rodoviario_l'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOC_Cidade_P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_objeto', models.FloatField()),
                ('nome', models.CharField(max_length=100)),
                ('nomeabrev', models.CharField(max_length=50)),
                ('geometriaa', models.CharField(max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
