# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0018_loc_cidade_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loc_cidade_p',
            name='geometriaa',
            field=models.CharField(max_length=10),
        ),
    ]
