# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 17:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundo', '0019_auto_20160505_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcMunicipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_municip', models.CharField(max_length=60)),
                ('cd_geocmu', models.CharField(max_length=7)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
